### ISSUE TITLE
Ferdium no longer respects switching to dark mode for all services

### ISSUE THREAD

**Issue by 392781** [ferdium/ferdium-app#1348]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.1?

### Expected Behavior

When the OS switches to dark mode, Ferdium and all its services will switch to dark mode as well.

### Actual Behavior

Ferdium side bar switches to dark mode but services *do not*.  They only switch upon reloading all of Ferdium (or closing out and reopening).

### Steps to reproduce

1. Open Ferdium.
2. Force your OS to switch between light and dark mode.
3. Notice that Ferdium services do not switch to dark mode.

**Comment by Tommimon** [comment]
Same issue, I tried with WhatsApp and Telegram and it didn't work, I don't know if other services do.

Os: nixos
Ferdium: 6.4.1

**Comment by meiphoo7-Mae** [comment]
I reported a similar problem in #448 over a year ago and apparently Electron is to blame.

**Comment by DavidDJPearl** [comment]
None of the services I use respond to enabling dark mode and I'm yet to see it function in the first place.  This is a known issue.

**Comment by meiphoo7-Mae** [comment]
@DavidDJPearl And your OS is?

On Kubuntu it does work provided dark mode is enabled system-wide like for example the theme "Breeze Dark".
If you don't use that I guess you're on your own because bugs reports related to Linux remain mainly unattended for AFAICT.

**Comment by DavidDJPearl** [comment]
@meiphoo7-Mae,

Hi and my apologies for not providing any specifics.  I am running 6.6.1-nightly.14 on Windows 11 version 23H2, build 22631.2792, with Windows Feature Experience Pack 1000.22681.1000.0.  Let me know if there is any other info that might help.

**Comment by meiphoo7-Mae** [comment]
@DavidDJPearl I'm not a developer so I can't help with this. Because you're a Windows user while this issue is about Linux, which is mentioned in the opening post, it is probably better when you open a new issue. This has also the added benefit that you can provide details in the issue template.

**Comment by Tommimon** [comment]
From what I can see now the issue has been solved, at least for the services I use, we may consider closing this.

**Comment by sudoshindo** [comment]
> From what I can see now the issue has been solved, at least for the services I use, we may consider closing this.

May I know which services you use in Ferdium?

**Comment by Tommimon** [comment]
> May I know which services you use in Ferdium?

Telegram and WhatsApp

**Comment by sudoshindo** [comment]
I decided to try Ferdium again today to check dark mode behavior. Unfortunately Gmail still doesn't go dark at all.

I even browsed and tried several Dark Gmail stylesheets that I found. Pasting the CSS into user.css or darkmode.css and reloading Ferdium afterwards did nothing, absolutely zero changes were applied to the page.

I guess Universal Dark Mode is just destined to be broken and inconsistent.

**Comment by Cozynezz** [comment]
hey, same problem here, darkmode didnt work :(

**Comment by pegasusearl** [comment]
same problem for Gmail for me.

Version: 7.0.0
Server: No Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: Windows 10
Arch: x64
Build date: Sun Nov 10 2024 09:23:00 GMT+0700 (Western Indonesia Time)
Git SHA: e6249427
Git branch: release

**Comment by athyfr** [comment]
Same problem for me. (Gmail)

**Comment by Arno989** [comment]
I've been having this problem too for a while now with whatsapp.
After every restart I had to disable and re-enable dark mode for it to apply.
During my search just now I came across [this](https://github.com/ferdium/ferdium-app/issues/939#issuecomment-1424717014) comment that suggests using the in-app darkmode setting.
I disabled dark mode for whatsapp in ferdium and then turned darkmode on in whatsapp itself. This seems to persist after a restart of ferdium.

**Comment by tildebyte** [comment]
Google Mail & Calendar work with Ferdium here - but I've set the native option to use dark mode *outside of* Ferdium...
