### ISSUE TITLE
WhatsApp Log in screen hangs

### ISSUE THREAD

**Issue by pbalog5154** [ferdium/ferdium-app#1975]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

7.0.0 Portable

### Recipe Name

WhatsApp

### Recipe Version

3.5.7

### Last Known working version of the recipe

I never used WhatsApp in Ferdium before

### Steps to reproduce

1. Add WhatsApp service with default settings (or any other settings)
2. Switch to the WhatsApps service
3. Notice QR code doesn't load to the interface and links don't react (e.g. Log in with phone number)

### Expected Behavior

Log in interface expected to load the content of https://web.whatsapp.com/

### Actual Behavior

Log in interface doesn't load fully

### Screenshots

![2024_11_21_062](https://github.com/user-attachments/assets/0597044f-7d24-40e2-9a9e-b6b04699c9f6)

**Comment by ubeyou** [comment]
same issue happened after logged out and trying to login, any fixes available? tried clear cache and reload services, still stuck at QR stage

**Comment by bllngr** [comment]
Same problem with Ferdium-win-Portable-7.0.0-x64 and Portable-7.0.1-nightly.4-x64. For some weird reason, disabling the "stay logged in" options makes the QR code load. Re-enabling it breaks it again.

Toggling the checkbox breaks the functionality of the "log in with phone number" link as well.

Update: Still happening with 7.1.0-nightly.6

**Comment by fernando-garrido** [comment]
The problem continues in the version 7.1.0-Portable, exactly as described by @bllngr above.
