### ISSUE TITLE
Bug: Reordering services doesn't work properly

### ISSUE THREAD

**Issue by IceBeach7** [ferdium/ferdium-app#293]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.63

### What Operating System are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Ferdium version

-

### Expected Behavior

Services would be ordered if I drag them.

### Actual Behavior

Services jump to a seemingly random location, some jump to the original location.

### Steps to reproduce

1. Hold a service
2. Drag it to any position

### Additional information

- The OS is set to German.
- It only happens inside workspaces. Reordering in "All services" works.

**Comment by NathanaelGandhi** [comment]
I'm assuming you have added services and then are trying to order them in the left-most bar. 
On 6.0.0-nightly.60 and 6.0.0-nightly.67 (Arch Linux) (Lang: English) I'm not experiencing this problem. 

@IceBeach7 Does it jump while dragging or only after release?

**Comment by IceBeach7** [comment]
@NathanaelGandhi It jumps after I release it.

**Comment by SpecialAro** [comment]
Can't reproduce this on Windows 11

**Comment by IceBeach7** [comment]
I have noticed that it's only broken if you have selected a workspace.
If I select "All services", it works normally.

**Comment by SpecialAro** [comment]
> I have noticed that it's only broken if you have selected a workspace.
> If I select "All services", it works normally.

Oh! Ok, so this is inside a workspace. This is very important information, please update the issue accordingly

**Comment by cino** [comment]
I'm not able to reproduce this issue on the latest version (develop) while switching between workspaces like a mad man :) Tested it on MacOS myself.

**Comment by IceBeach7** [comment]
Weirdly, the bug doesn't occur with the first 3 services.

**Comment by SpecialAro** [comment]
Do you have the recipes name shown on the sidebar?

**Comment by mp-strachan** [comment]
Can reproduce on Ubuntu 22.04 with Ferdium 6.0.0-nightly.75.

- No recipe names enabled.
- Slim sidebar size.
- Normal icon size.

"All services": can rearrange icons no issue
If I go into a workspace: cannot rearrange icons. Will either jump back to where they were, or to a random place.

**Comment by IceBeach7** [comment]
I only don't have the names shown.

**Comment by harryfear** [comment]
I have no workspace(s) and this issue affects all my services; they are non-draggable so no reordering is possible.

v. 6.0.0.-nightly.59 on macOS.

**Comment by cino** [comment]
@harryfear Please update to the latest nightly/beta and check again, there are many fixes between 59 and the latest.

**Comment by harryfear** [comment]
I get a 404 on "https://github.com/ferdium/ferdium-app/releases/download/v6.0.0-nightly.82/latest-mac.yml"

![Screenshot 2022-06-30 at 20 54 44](https://user-images.githubusercontent.com/907604/176765556-77e2bbd8-2d82-4d2b-86d6-d6909eee259a.png)

**Comment by harryfear** [comment]
This issue now seems resolved in [6.0.0-nightly.81](https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.81).

**Comment by cino** [comment]
@harryfear That is a known issue we are actively working on in , #404 please download the latest releases from the releases page for now :)

**Comment by vraravam** [comment]
Moreover, nightly 59 did not have the in-app updates at that point in time.

**Comment by IceBeach7** [comment]
Still happening for me in 6.0.0-nightly.86.

**Comment by vraravam** [comment]
@IceBeach7 - do you have the service names enabled and showing? There was a bug where, if the service names were visible, then DnD was broken - but this has also been fixed in the past couple of weeks. I am not able to reproduce this bug in macos. I'm running the latest build (nightly 86)

**Comment by IceBeach7** [comment]
@vraravam No, I have never turned them on since installation.

**Comment by SpecialAro** [comment]
@IceBeach7 can you please take a screenshot of the Services Menu while inside a Workspace that's facing this issue?

This may occur if thee Services have a wrong index.

Also, is this still an issue with the latest nightly?

**Comment by jeroni** [comment]
Still happening...

Version: 6.0.1-nightly
OS: Arch linux
DE: Gnome 42.3

https://user-images.githubusercontent.com/9005992/180403714-e3a1e8e8-ee34-4a97-906a-469e11f21f58.mp4

**Comment by cyberjunkie-android** [comment]
I'm running version 6.0.0  on Windows 10.

I was trying to rearrange the order of the services in the sidebar for my workspace, but haven't had consistent results.  

- Sometimes I would drag them and they would move to where I wanted. 
- And other times it would move elsewhere, not where I had dropped the service icon. 
- Then it seams most of the time they will not move, when I would release the service icon it would snap back to where it was originally..

**Comment by cyberjunkie-android** [comment]
I just checked how it worked on the all services workspace, and it worked fine. There was no problems in rearranging the services. But on one of my created workspaces I still had my problems.

**Comment by IceBeach7** [comment]
> Still happening...
> 
> Version: 6.0.1-nightly OS: Arch linux DE: Gnome 42.3
> reordering.not.working.mp4

I have the same behavior on 6.0.1-nightly.7

**Comment by Gaibhne** [comment]
Still happening in 6.2.0. Able to sort in "All services", but not in workspaces. Sometimes it works, usually it doesn't, sometimes other services get reordered that I didn't touch. Works on one machine but not on another, with identical Ferdium versions and settings. Service name display does not seem to make a difference.

**Comment by alephtaph** [comment]
Bug still with me too:
OS: Mac 13.2.1
Ferdium APP: 6.2.4

Sorting is working fine in "All services" but not in any of the Workspaces.

**Comment by kaleben0** [comment]
So I have been fiddling with this and I think I have a work around. 

It seems that when it comes to Workspaces, the service icons are in order by which they are selected in the Workspaces customization screen. 

If you de-select all the services in a Workspace, then re-select them in the order you want them to be in, then it should work. 

![Untitled-1](https://github.com/ferdium/ferdium-app/assets/52037180/cc6615c2-65bc-4bfe-a074-13e7522e913c)

**Comment by 3gmgithub** [comment]
FYI I this still is not fixed v6.7.0 on Ubuntu v22.04
I had to deselect and reselect and that appeared to work...
But the drag and drop like the 'All Workspaces' does not work still.
