### ISSUE TITLE
Bug: software won't start, it show in win taskbar, portable working perfect

### ISSUE THREAD

**Issue by tal-yt** [ferdium/ferdium-app#810]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0 + 6.2.1

### What Operating System are you using?

Windows

### Operating System Version

win 10 pro 21H2 19044.2251

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.0

### Expected Behavior

app start when i press icon

### Actual Behavior

start to happen a week ago.
app not start (6.2.0 and 6.2.1) at all, it show in win task bar
try to reinstall, it say it open and cannot close it.
I delete the files and make 6.2.0 and 6.2.1 install and same issue continue
PORTABLE version working perfect :)

### Steps to reproduce

I guess its something in my computer
please help me fix or fully clear installation files.
I will try to re-install again and hope it work

### Screenshots

![image](https://user-images.githubusercontent.com/119488480/204753504-1bd5ad17-c898-4ca6-ad5b-581035536d83.png)

**Comment by vraravam** [comment]
Are you trying to install 2 different versions of Ferdium at the same time? ie 6.2.0 AND 6.2.1?

**Comment by tal-yt** [comment]
hey, no.
I was in latest 6.2.0 and it work o.k until last week.  I try to reinstall - no luck, try to uninstall and delete folder file and install - also no luck.
today new version came out 6.2.1, gave it a try and same problem.
when I press Ferdium.exe it open 3 Ferdium in windows task bar each time i press.

edit: I delete = AppData\Local\Programs\ferdium

**Comment by SpecialAro** [comment]
Also, what files did you removed? Did you blow out %appdata%/Ferdium?

**Comment by vraravam** [comment]
Please use the `Help` > `Import/Export Configuration Data` to at least backup your profile before blasting it away.

**Comment by Satadaes** [comment]
> Please use the `Help` > `Import/Export Configuration Data` to at least backup your profile before blasting it away.

I'm having a similar issue except it goes all purple and I can't do anything, can I still backup? Where is that tool?

example - https://gyazo.com/9f5edbbea67a78de673224f1732de6cc

**Comment by tal-yt** [comment]
> > Please use the `Help` > `Import/Export Configuration Data` to at least backup your profile before blasting it away.
> 
> I'm having a similar issue except it goes all purple and I can't do anything, can I still backup? Where is that tool?
> 
> example - https://gyazo.com/9f5edbbea67a78de673224f1732de6cc

hey Satadaes, I backup mine on the website online :) hope it helps

**Comment by Iuxelle** [comment]
The same thing happen to me too. In my case, i tried pressing ctrl+tab and it loads perfectly... try it too! see if it works.

**Comment by tal-yt** [comment]
Just small update, still happens in 6.2.2 :(

**Comment by DynaDASH** [comment]
Hello, I want to share my case, kinda similar but honestly feels way worse, you'll see why.

Ferdium loads as a Background Process and that's it, nothing else, no blue screens, no taskbar, no nothing, just the void. Actually, whenever I try to kill the processes they just come back so I have to be quick but nothing positive comes out of it, the app never becomes... an app. I can't use Ferdium and I've been dealing with this for weeks. I don't know what to do and I usually don't write to developers as I try to research on my own first... I'm just out of ideas.

Although, as the OP mentioned, the Portable Version works perfectly, I just don't know what happened with the non-portable one.

I use Windows 11. I don't know if you require something else from me, but for me to actually finally redact this whole ordeal means I'm truly desperate, haha.

**Comment by vraravam** [comment]
Please try with the latest nightly. This should have been fixed by #838 . Once you confirm, we can close this ticket.

**Comment by DynaDASH** [comment]
Dunno if this is for the OP or for me (or both), but I can't verify this nightly since I'm traveling and this is happening with my desktop PC.

Fortunately I'm not having this issue with my laptop. I'll report if this update fixed my issue possibly next week.

Happy holidays.

**Comment by NithyaMenon** [comment]
@vraravam I just had the same issue and can confirm that using the latest nightly (Portable version) fixed the problem for me.

**Comment by vraravam** [comment]
Thanks for the confirmation @NithyaMenon ! Closing the issue now.

@SpecialAro @balajiv113 @muhamedsalih-tw @Alphrag - do you think we can release a new stable version to fix this? If a couple of you agree, then we can release even immediately - since we haven't had any commits in the past 2-3 days.

**Comment by balajiv113** [comment]
@vraravam The fix we done (disabling sentry) is more to find if that is the root cause right ??

If disabling sentry is fine from ferdium pov then yes we can release stable. Else i think we need to first make ferdium work well with sentry before stable release

**Comment by vraravam** [comment]
OTOH, the current stable release seems unusable by Windows users who do not want to move to the nightly. In this condition, and considering that we released some past stable versions without sentry, imo, we can do 1 more such release, and later try to find the workaround/solution for sentry to be enabled.

**Comment by Alphrag** [comment]
I would indeed prefer to push a release out so that the behaviour is stable for all users. We haven't really used the information we could get from sentry but it has given us multiple problems. So I am happy to keep it disabled until we can find the root of the problem before putting it back in.

**Comment by SpecialAro** [comment]
I totally agree with the 3 of you. Releasing a stable version that is working consistently for all OSes should be the priority.

Then, we can try to fix Sentry and test it in Beta versions before releasing yet another stable 😁

**Comment by NithyaMenon** [comment]
hey @vraravam i'm still seeing that the new release actually doesn't solve the issue for me. so i've gone back to the "portable nightly" which solves the problem 🤷
