### ISSUE TITLE
Bug: Stuck on purple screen after Macbook wake up since 6.2.4 update

### ISSUE THREAD

**Issue by sy6sy2** [ferdium/ferdium-app#923]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

macOS

### Operating System Version

macOS 12.6.2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.3

### Expected Behavior

When I open my MacBook Pro lid I expect to have Ferdium working with my services (like it was with 6.2.3).

### Actual Behavior

Since the 6.2.4 update, each time I open my MacBook Pro, Ferdium is stuck on the purple screen. If I try to reload Ferdium it won't work. The only way to fix this is to quit Ferdium and re-open it.

### Steps to reproduce

1. Open Ferdium on your Macbook
2. Close your Macbook lib
3. Wait a little ....
4. Open your Macbook
5. Ferdium is stuck on the purple screen.

### Debug link

https://debug.ferdium.org/77b84d6b-2f76-41f3-ad75-14d4e865b43b

**Comment by whatisthisidont** [comment]
same here

**Comment by micoli** [comment]
Exactly the same for me. Glad to help on testing a new version if available


Version: 6.2.4
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: macOS
Arch: arm64
Build date: Sat Jan 28 2023 00:32:12 GMT+0100 (heure normale d’Europe centrale)
Git SHA: 68e85c3e
Git branch: release


Thanks by advance

**Comment by MazzMat** [comment]
+1

Version: 6.2.4
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: macOS
Arch: arm64
Build date: Sat Jan 28 2023 00:32:12 GMT+0100 (Ora standard dell’Europa centrale)
Git SHA: 68e85c3e
Git branch: release

**Comment by hnykda** [comment]
same here on ventura

**Comment by krptg0** [comment]
Same on Ventura also.

**Comment by vraravam** [comment]
Please try the latest nightly, I dont have such issues with that. I just released [6.2.6-nightly.4](https://github.com/ferdium/ferdium-app/releases/tag/v6.2.6-nightly.4)

Also, 6.2.5 was released a couple of weeks ago, have you upgraded to that? If not, any particular reason?

**Comment by hnykda** [comment]
Mostly because the default brew package hasn't been updated... I am installing https://github.com/ferdium/homebrew-ferdium nightly and will report back.

**Comment by vraravam** [comment]
oh ok - i forgot to approve and merge those PRs, and have just done so.

**Comment by hnykda** [comment]
OK, still happens:

```
Version: 6.2.6-nightly.4
Server: Ferdium Server
Electron: 23.1.3
Chrome: 110.0.5481.179
Node.js: 18.12.1
Platform: macOS Unknown
Arch: arm64
Build date: Sun Mar 12 2023 02:03:36 GMT+0100 (Central European Standard Time)
Git SHA: 35206504
Git branch: nightly
```
I am on Macbook Air M2

This is how it looks like:
![2023-03-13_13-45](https://user-images.githubusercontent.com/2741256/224705929-74e6f2af-ae71-4534-84e0-5260fa4e1e6e.png)
clicking on anything doesn't work (I can e.g. select Ferdium -> About ferdium in the menu but it doesn't do anything). I have to force kill the app and start it again. Works afterwards.

**Comment by alexyjasper** [comment]
Same.   Usually happens after a weekend rather than an overnight sleep. 

> Version: 6.2.4
Server: No Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: macOS
Arch: arm64
Build date: Fri Jan 27 2023 15:32:12 GMT-0800 (Pacific Standard Time)
Git SHA: 68e85c3e
Git branch: release

**Comment by josecastillolema** [comment]
It also happens on Linux:
- Fedora 39
- Wayland

**Comment by vraravam** [comment]
Please do not report bugs against an older version of Ferdium. Please try with the latest version, and if its reproducible, please specify the Ferdium version. Its impossible to test against such an old version (6.2.4)!

**Comment by SpecialAro** [comment]
Closing due to inactivity.
